### ISSUE TITLE
WARNING - Provider 'podnapisi' is not available, discarding it

### ISSUE THREAD

**Issue by bokiroki** [caronc/nzb-subliminal#44] opened 2017-12-13 22:57 UTC
Hi, can i ask few questions?

First one is in the title. I installed nzb-subliminal yesterday, and from begining i geting this warning.. i plan to use podnapisi only, because there are good amount of serbian/croatian subtitles.. with opensubtitles i sometimes get subtitles that are copy paste from google translator..other providers dont have serbian/croatian subs..

Second question.. i'm using raspberry pi 3 with minidlna, so my srt file name must be the same like video file..podnapisi or opensubtitles sometimes dont have my primary serbian language srt file so i wanna add croatian language in command line -l sr,hr   but than if two languages exist, subliminal will download both languages with rs.srt and hr.srt and than subtitle will not work on minidlna.. can i put two languages  -l sr,hr and download only one subtitles with -s command

~~Third one.. i made a test.sh file from command line and put that file in the same folder where subliminal.py and subliminal folder is:
#!/bin/bash~~

~~python Subliminal.py -s -f -l sr,hr -p podnapisi,opensubtitles -e Windows-1250 -S
/mnt/dietpi_userdata/Video~~

~~and made that script executable with:
chmod a+x test.sh~~

~~when i test it with double click, everything work, so i put that test.sh in sonarr custom script to be triggered after sonarr download episode and i get error in sonarr log "python: can't open file 'Subliminal.py': [Errno 2] No such file or directory" what i'm doing wrong?~~
I managed to work out third question

And last one.. Titlovi.com is by far the best subtitles provider for Bosnian/Croatian/Macedonian/Slovenian/Serbian languages..there is a official Titlovi.com kodi plugin in the work  https://github.com/tturkalj/service.subtitles.titlovi-com-official
How hard will it be to implement that code in your program?

Thanks for your time..

**Comment by caronc** [comment] 2017-12-14 19:25
Thanks for your feedback.  I'll try to address your questions from what i know/think now:

1. I'll definitely have to look into why podnapisi isn't working  and get back to you.  I need to investigate that a bit more.
2. having the filename named the same as the video file is the normal way of doing things.  if you add the **-s** (**--single**) switch, the **.srt** file will be exactly the same.  But the catch is you can only have 1 subitle file then.  If you need to accommodate multiple languages, then you're doing it right by just downloading the **.sr.srt** and **.hr.srt** copies. Most video applications are smart enough to still interpret these filenames (or should anyway).
3.  Good job on figuring this out before I had time to reply! :smile:
4. This is a tough one; the problem isn't with you or your request.  it's dealing with websites that are non-English. It's very similar to another open issue (#26) which has been open forever unfortunately.   i will check out the github page you provided at least and see if it would be easy to integrate or not. I just don't want to give you false hope or promise anything here; at least not at this time (sorry).

**Comment by bokiroki** [comment] 2017-12-14 20:13
About second question..i'm using Readymedia (minidlna) dlna server and it not support multiple language files.. i propose if you can tweak the code:
When user put -s and -l fr,en.. -s will lose it's function, so if user put -s and -l fr,en single srt file will be downloaded either fr language or english language..so if one language is aviable, just one srt will be downloaded like usual, but if two languages are aviable, only one with best score will be downloaded

About 4 question.. i looked code and everything is in english, if you need some testing i can help..and i can ask owner of code for aditional help if is needed
Thanks

**Comment by caronc** [comment] 2018-01-23 14:08
This was done for some time; but it appears i failed to notify you here and ask you to try it out again. You'll need to pull from the master branch.

**Comment by bokiroki** [comment] 2018-01-24 00:36
Hi , it's my fault, i installed new version that day when you updated and didnt told you..
so for few days i tested it, and everything was ok, only minor problem was that when i select two languages with new -s command, one srt will be downloaded but two encoding messages will be displayed in terminal..

and i puted script in crontab since than and didnt look what is it doing, and today i tested it again, and i got error with podnapisi, i tried 3 times, and every time i got error

boki@mojskae34:/home/dietpi/nzb-subliminal-master# python /home/dietpi/nzb-subliminal-master/Subliminal.py -f -s -l sr,hr -p podnapisi,opensubtitles -S /mnt/dietpi_userdata/MiniDLNA
2018-01-24 01:16:36,364 - 21443 - INFO - Found 12 matched file(s).
2018-01-24 01:16:36,364 - 21443 - INFO - Using advanced search mode
2018-01-24 01:16:37,403 - 21443 - INFO - Scanning video 'The.Disaster.Artist.2017.DVDScr.XVID.AC3.HQ.Hive-CM8[oscars].avi' in '/mnt/dietpi_userdata/MiniDLNA/Boris/Filmovi/The Disaster Artist'
2018-01-24 01:16:48,081 - 21443 - INFO - Listing subtitles with provider 'opensubtitles' for video <Movie [u'The Disaster Artist', 2017]> with languages set([<Language [hr]>, <Language [sr]>])
2018-01-24 01:16:54,895 - 21443 - INFO - Found 0 subtitle(s) on opensubtitles
2018-01-24 01:16:54,895 - 21443 - INFO - Listing subtitles with provider 'podnapisi' for video <Movie [u'The Disaster Artist', 2017]> with languages set([<Language [hr]>, <Language [sr]>])
2018-01-24 01:16:59,161 - 21443 - INFO - Found 0 subtitle(s) on podnapisi
2018-01-24 01:17:06,018 - 21443 - WARNING - No subtitles were found for The.Disaster.Artist.2017.DVDScr.XVID.AC3.HQ.Hive-CM8[oscars].avi
2018-01-24 01:17:06,266 - 21443 - INFO - Scanning video 'Limitless.2011.UNRATED.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv' in '/mnt/dietpi_userdata/MiniDLNA/Boris/Filmovi/Limitless'
2018-01-24 01:17:13,398 - 21443 - INFO - Listing subtitles with provider 'opensubtitles' for video <Movie [u'Limitless', 2011]> with languages set([<Language [hr]>, <Language [sr]>])
2018-01-24 01:17:13,555 - 21443 - INFO - Found 0 subtitle(s) on opensubtitles
2018-01-24 01:17:13,556 - 21443 - INFO - Listing subtitles with provider 'podnapisi' for video <Movie [u'Limitless', 2011]> with languages set([<Language [hr]>, <Language [sr]>])
2018-01-24 01:17:18,159 - 21443 - ERROR - Unexpected error in provider 'podnapisi'
Traceback (most recent call last):
  File "/home/dietpi/nzb-subliminal-master/Subliminal/subliminal/api.py", line 256, in download_best_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_video_languages)
  File "/home/dietpi/nzb-subliminal-master/Subliminal/subliminal/providers/podnapisi.py", line 327, in list_subtitles
    year=video.year)]
  File "/home/dietpi/nzb-subliminal-master/Subliminal/subliminal/providers/podnapisi.py", line 266, in query
    'replace',
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 27: ordinal not in range(128)
2018-01-24 01:17:18,315 - 21443 - WARNING - No subtitles were found for Limitless.2011.UNRATED.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv

**Comment by caronc** [comment] 2018-01-24 15:52
Thanks for sharing that! I'll have a look at it this weekend and see what's going on here.

**Comment by caronc** [comment] 2018-01-28 18:38
This last push should look after your Podnapisi issue you were facing.

**Comment by bokiroki** [comment] 2018-01-28 22:20
Thank you, i will test it after i get from work..
can i ask two questions:
Sometimes subliminal download bad subtitle (bad timing), very rarely, but it's happen.. Is there are method in nzb subliminal so that subtitle can be replaced or i must manually replace that subtitle?
And second question, for some new movies it can be days for subtitles to appear, and i manually look from time to time to see is subtitle is downloaded ..i see that you developed handy script nzb-notify, can that script be used to notify when subtitle is downloaded?

**Comment by caronc** [comment] 2018-01-29 15:55
> Sometimes subliminal download bad subtitle (bad timing), very rarely, but it's happen.. Is there are method in nzb subliminal so that subtitle can be replaced or i must manually replace that subtitle?

I have the same experience as you.  There is nothing you can really do in these cases.  Subtitles are matched against the release group, audio and video details along with the name, language, etc.  They're all weighted and some subtitles are just labeled wrong on these sites.  The incorrect subs you get in these cases matched against all of this criteria.  It's hard to automate whether something is a duck or not if it really says it's a duck. :smile:.

The best you can do is wait a while (a day or two) and try again. Also know that you're not the only one who is getting these mismatched files on whatever show/movie is in question. Sometimes the people who maintain these correct them and everything is okay again.  Otherwise, the manual route might be the only next best thing (what you're doing).

So the short answer is: Try again later and sometimes a manual retrieval is all you can do.

**That all said**: If you can give me examples of a specific show that you can match against on a subtitle website that is wrong when clearing the right one is right there, I can have a closer look.  Perhaps the weighting system can be tweaked.  I'll need the debug output in these cases so i can follow where it goes wrong.

> .i see that you developed handy script nzb-notify, can that script be used to notify when subtitle is downloaded?

[nzb-notify](https://github.com/caronc/nzb-notify) is (now) a wrapper for [apprise](https://github.com/caronc/apprise).  nzb-notify's primary function is to just notify you when SABnzbd or NZBGet handle tasks (alerts you when a download is complete and whether it was successful or not).

Being notified when subtitles download though is an interesting idea; I personally wouldn't use that, but i could see value in it. If you use the _nzb-notify_ script as is (today), and set NZBGet to call it.  It will provide you a listing of all video files retrieved and in that list you can see the subtitles too.  So you can sort of already do this (know if the subs came down).  But it won't tell you when subs are downloaded later (if that's the case) if you're using the scan-script portion of this tool.

**Comment by bokiroki** [comment] 2018-01-29 16:28
Thanks for explanation..aboit second question..i use radarr and sonarr for torrents, so terminal is my only choice..is there a way if nzb-subliminal download a subtitle to trigger a custom script? That script will be a nzb notify..but in that way we will not have name of the file, or it can be implemented?
In either way, if you gonna come with some implementation it will be great, if not, its great to..i wanna thank you again, great support so far from you :)

**Comment by caronc** [comment] 2018-01-29 17:24
No problem; I'm happy to help out!

I also created issue #47 to address your notification feature of this script. I can't promise a delivery time; but I will definitely address it at some point!

In the meantime, I'm going to close this ticket for now as i think we've covered the issues in it. Please feel free to request it be reopened in the future or just create another ticket if you ever have any more issues! :smile:

**Closed by caronc** 2018-01-29 17:24 UTC
Labels: Investigating, bug
