### ISSUE TITLE
Do you support composite language codes?

### ISSUE THREAD

**Issue by msdos** [caronc/nzb-subliminal#67] opened 2018-11-22 05:25 UTC
`subliminal` accepts `pt-br`, but your script only accepts `pt`. Is this the intended behavior?

**Comment by caronc** [comment] 2018-11-22 22:17
Yeah, the issue isn't so much the script, but the fact that most of the actual subtitle websites don't support the composite IDs either. :pensive:

**Comment by caronc** [comment] 2018-12-17 19:08
Hi, I'm just going to close this ticket as i hadn't heard back.

Feel free to re-open it and/or comment on it if you have any more questions.

**Closed by caronc** 2018-12-17 19:08 UTC
Labels: question
